### ISSUE TITLE
Test Redis version to throw custom Exception

### ISSUE THREAD

**Issue by stephpy** [jeremyFreeAgent/Bitter#8]
I've test which fails, due to BITOP and BITCOUNT commands which are unknown. 

I guess it's due to my version of redis, imo we should add in composer a require for redis server version.

**Comment by jeremyFreeAgent** [comment]
The required version of Redis is in the README. It's 2.6. But yes, its can be in composer.

**Comment by stephpy** [comment]
Yes, that's better to inform user with a custom exception IMO

**Comment by tonypiper** [comment]
actually, @stephpy, I had the same problem - I am running redis server 2.6 BUT snc_redis by default is expecting to work with 2.4, so you have to add a 'profile' option to your snc_redis configuration in `config.yml`.

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            options:
                profile: 2.6
```

worth adding to the readme, @jeremyFreeAgent?
